---
- name: Enable to install NGINX.
  shell: amazon-linux-extras enable nginx1
  become: yes

- name: Install NGINX.
  yum:
    name: nginx

- name: Configure NGINX.
  template:
    src: healthcheck.conf
    dest: /etc/nginx/default.d/

- name: ReStart NGINX.
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
